import React, { useState, useEffect, useRef } from 'react';
import { PackingResult, PlacedItem, Dimensions } from '../types';
import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';

interface VisualizerProps {
  data: PackingResult | null;
  onPackageClick?: (id: string) => void;
}

// --- PDF TEMPLATE COMPONENT ---
// This component is hidden from the user but used by the code to "render" the PDF pages
const PDFExportTemplate = React.forwardRef<HTMLDivElement, { 
    data: PackingResult, 
    layerIndex: number, 
    mode: 'cover' | 'layer' 
}>(({ data, layerIndex, mode }, ref) => {
    
    // Helper to find unique items for the Legend
    const uniqueItems = React.useMemo(() => {
        const map = new Map();
        data.placedItems.forEach(item => {
            // Key by dimensions + color to distinguish types
            const key = `${item.label}-${item.color}`;
            if (!map.has(key)) {
                map.set(key, item);
            }
        });
        return Array.from(map.values());
    }, [data]);

    const currentZ = data.layers[layerIndex] || 0;
    
    // Filter items for the specific layer view
    const activeItems = mode === 'layer' ? data.placedItems.filter(item => {
        const epsilon = 0.5;
        // Show items that exist at this depth
        return item.z <= currentZ + epsilon && (item.z + item.length) > currentZ + epsilon;
    }) : [];

    return (
        <div ref={ref} className="bg-white text-slate-900 font-sans relative overflow-hidden" style={{ width: '1024px', height: '768px' }}>
            
            {/* --- MODE: COVER PAGE (Tutorial & Legend) --- */}
            {mode === 'cover' && (
                <div className="p-12 h-full flex flex-col">
                    <header className="border-b-4 border-slate-900 pb-6 mb-8 flex justify-between items-end">
                        <div>
                            <h1 className="text-5xl font-black text-slate-900 mb-2">Load Plan Report</h1>
                            <p className="text-xl text-slate-500">Generated by PackMaster 3D</p>
                        </div>
                        <div className="text-right">
                            <div className="text-sm font-bold uppercase text-slate-400">Container Dimensions</div>
                            <div className="text-2xl font-bold">{data.containerDimensions.length} x {data.containerDimensions.width} x {data.containerDimensions.height}</div>
                            <div className="text-sm text-slate-400 mt-1">Utilization: {Math.round(data.volumeUtilization)}%</div>
                        </div>
                    </header>

                    <div className="flex-1 grid grid-cols-2 gap-12">
                        {/* Section 1: Loading Strategy */}
                        <div className="bg-slate-50 p-8 rounded-3xl border border-slate-200">
                            <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">
                                <span className="w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center text-sm">1</span>
                                Loading Strategy
                            </h2>
                            <div className="flex flex-col items-center justify-center h-64 relative">
                                {/* Simple CSS Diagram of Container */}
                                <div className="w-48 h-64 border-4 border-slate-800 rounded-lg relative flex flex-col justify-end p-4 bg-white shadow-sm">
                                    <div className="absolute top-0 left-0 w-full h-8 bg-slate-200 border-b border-slate-300 flex items-center justify-center text-[10px] font-bold text-slate-500">FRONT (DOOR)</div>
                                    <div className="flex-1 flex items-center justify-center">
                                        <div className="flex flex-col items-center gap-2">
                                            <div className="text-sm font-bold text-slate-400">LOAD DIRECTION</div>
                                            <svg className="w-12 h-12 text-brand-600 animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M5 10l7-7m0 0l7 7m-7-7v18" /></svg>
                                        </div>
                                    </div>
                                    <div className="w-full h-12 bg-slate-800 rounded flex items-center justify-center text-white font-bold text-xs">
                                        BACK WALL (Start Here)
                                    </div>
                                </div>
                                <p className="mt-4 text-center text-slate-600 text-sm max-w-xs">
                                    <strong>Critical:</strong> Always load items starting from the <span className="text-slate-900 font-bold">Back Wall</span> (Depth 0) moving towards the <span className="text-slate-900 font-bold">Front Door</span>.
                                </p>
                            </div>
                        </div>

                        {/* Section 2: Box Legend */}
                        <div className="bg-slate-50 p-8 rounded-3xl border border-slate-200 overflow-hidden flex flex-col">
                            <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">
                                <span className="w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center text-sm">2</span>
                                Package Legend
                            </h2>
                            <div className="flex-1 overflow-y-auto space-y-4 pr-2">
                                {uniqueItems.map((item, i) => (
                                    <div key={i} className="flex items-center gap-4 bg-white p-3 rounded-xl border border-slate-100 shadow-sm">
                                        <div className="w-12 h-12 rounded-lg shadow-inner shrink-0" style={{ backgroundColor: item.color }}></div>
                                        <div>
                                            <div className="font-bold text-lg leading-none">{item.label}</div>
                                            <div className="text-xs text-slate-500 mt-1 font-mono">
                                                Dims: {Math.round(item.width)}W x {Math.round(item.height)}H x {Math.round(item.length)}D
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                            <div className="mt-4 text-xs text-slate-400 italic">
                                * Check specific steps for rotation requirements.
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* --- MODE: LAYER VIEW --- */}
            {mode === 'layer' && (
                 <div className="w-full h-full flex flex-col relative">
                    <div className="absolute top-0 left-0 w-full bg-slate-50 p-6 border-b border-slate-200 flex justify-between items-center z-20">
                        <h1 className="text-3xl font-bold text-slate-800">Step {layerIndex + 1}</h1>
                        <div className="text-2xl font-mono text-slate-600">Depth Position: <span className="font-bold text-brand-600">{Math.round(currentZ)}cm</span></div>
                    </div>
                    
                    <div className="flex-1 flex items-center justify-center bg-slate-100 p-12">
                        {/* Render the container box similarly to the main visualizer but fixed size for PDF consistency */}
                         <div className="relative border-8 border-slate-800 bg-white shadow-xl" 
                             style={{
                                 width: '800px', // Fixed export width
                                 height: `${800 * (data.containerDimensions.height / data.containerDimensions.width)}px`,
                                 maxHeight: '600px'
                             }}>
                            {/* Inner Grid */}
                            <div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'linear-gradient(#000 1px, transparent 1px), linear-gradient(90deg, #000 1px, transparent 1px)', backgroundSize: '40px 40px' }}></div>

                            {activeItems.map((item, i) => {
                                const isNew = Math.abs(item.z - currentZ) < 0.5;
                                return (
                                    <div
                                        key={i}
                                        className="absolute flex items-center justify-center text-center overflow-hidden border border-slate-500"
                                        style={{
                                            left: `${(item.x / data.containerDimensions.width) * 100}%`,
                                            bottom: `${(item.y / data.containerDimensions.height) * 100}%`,
                                            width: `${(item.width / data.containerDimensions.width) * 100}%`,
                                            height: `${(item.height / data.containerDimensions.height) * 100}%`,
                                            backgroundColor: item.color,
                                            opacity: isNew ? 1 : 0.2, // Fade out old items more in PDF for clarity
                                            zIndex: isNew ? 10 : 0,
                                            boxShadow: isNew ? 'inset 0 0 0 2px rgba(255,255,255,0.5)' : 'none'
                                        }}
                                    >
                                        {isNew && (
                                            <div className="flex flex-col items-center justify-center leading-none">
                                                <span className="text-white font-bold text-xl drop-shadow-md">
                                                    {Math.round(item.width)}x{Math.round(item.height)}
                                                </span>
                                                {/* In PDF, we explicitly show the Z-depth of the item to help with placement */}
                                                <span className="text-white text-xs mt-1 opacity-90">L: {Math.round(item.length)}</span>
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                    
                    {/* Footer for Page Number */}
                    <div className="absolute bottom-4 right-6 text-slate-400 font-mono text-sm">
                        Page {layerIndex + 2} of {data.layers.length + 1}
                    </div>
                 </div>
            )}
        </div>
    );
});


const Visualizer: React.FC<VisualizerProps> = ({ data, onPackageClick }) => {
  const [currentLayerIndex, setCurrentLayerIndex] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  
  // PDF Refs and State
  const exportRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportMode, setExportMode] = useState<'cover' | 'layer'>('cover');
  const [exportLayerIndex, setExportLayerIndex] = useState(0);

  const [scale, setScale] = useState(1);

  useEffect(() => {
    if (data) setCurrentLayerIndex(0);
  }, [data]);

  useEffect(() => {
    if (!containerRef.current || !data) return;
    const updateScale = () => {
        if (!containerRef.current || !data) return;
        const { width, height } = data.containerDimensions;
        const isMobile = window.innerWidth < 768;
        const paddingW = isMobile ? 16 : 64; 
        const paddingH = isMobile ? 16 : 64; 
        const wrapperW = containerRef.current.clientWidth - paddingW;
        const wrapperH = containerRef.current.clientHeight - paddingH;
        if (wrapperW <= 0 || wrapperH <= 0) return;
        setScale(Math.min(wrapperW / width, wrapperH / height));
    };
    updateScale();
    const observer = new ResizeObserver(updateScale);
    observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, [data]);

  const handleDownloadPDF = async () => {
      if (!data || !exportRef.current) return;
      setIsExporting(true);

      try {
        // Initialize PDF: Landscape, Unit: px, Format: matches our export div
        const pdf = new jsPDF({
            orientation: 'landscape',
            unit: 'px',
            format: [1024, 768]
        });

        // --- STEP 1: GENERATE COVER PAGE ---
        setExportMode('cover');
        // Wait for React to render the cover mode
        await new Promise(r => setTimeout(r, 200)); 
        
        if (exportRef.current) {
            const coverImg = await toPng(exportRef.current, { cacheBust: true, pixelRatio: 2 });
            pdf.addImage(coverImg, 'PNG', 0, 0, 1024, 768);
        }

        // --- STEP 2: GENERATE LAYERS ---
        for (let i = 0; i < data.layers.length; i++) {
            setExportMode('layer');
            setExportLayerIndex(i);
            
            // Add new page
            pdf.addPage([1024, 768], 'landscape');
            
            // Wait for React to render the specific layer
            await new Promise(r => setTimeout(r, 100)); 

            if (exportRef.current) {
                const layerImg = await toPng(exportRef.current, { cacheBust: true, pixelRatio: 2 });
                pdf.addImage(layerImg, 'PNG', 0, 0, 1024, 768);
            }
        }

        pdf.save('PackMaster-Load-Plan.pdf');

      } catch (e) {
          console.error("Export failed", e);
          alert("Failed to generate PDF.");
      } finally {
          setIsExporting(false);
          setExportMode('cover'); // Reset
          setExportLayerIndex(0);
      }
  };

  if (!data) {
      return (
        <div className="w-full h-full flex items-center justify-center bg-slate-50 text-slate-400 flex-col gap-4 p-8 text-center">
             <div className="w-24 h-24 md:w-32 md:h-32 bg-slate-100 rounded-full flex items-center justify-center mb-2 shadow-inner">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 md:h-12 md:w-12 text-slate-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>
             </div>
             <h3 className="text-lg md:text-xl font-bold text-slate-700">Ready to Pack</h3>
             <p className="max-w-xs md:max-w-md text-sm md:text-base text-slate-500">Add your container and items in the Setup tab to generate a plan.</p>
        </div>
      );
  }

  const { layers, placedItems, containerDimensions } = data;
  const currentZ = layers[currentLayerIndex] || 0;
  const epsilon = 0.5;
  const activeItems = placedItems.filter(item => 
    item.z <= currentZ + epsilon && (item.z + item.length) > currentZ + epsilon
  );

  return (
    <div className="flex flex-col h-full bg-slate-100 font-sans relative">
        
        {/* HEADER TOOLBAR */}
        <div className="bg-white border-b border-slate-200 px-4 md:px-6 py-3 flex items-center justify-between shrink-0 shadow-sm z-20 gap-2">
            <div className="flex flex-col min-w-0">
                <div className="flex items-baseline gap-2">
                    <h2 className="text-lg md:text-xl font-bold text-slate-800 whitespace-nowrap">Step {currentLayerIndex + 1}</h2>
                    <span className="text-xs md:text-sm font-medium text-slate-400">/ {layers.length}</span>
                </div>
                <div className="text-[10px] md:text-xs font-mono text-slate-500 flex items-center gap-2 truncate">
                    <span className="inline-block w-2 h-2 rounded-full bg-brand-500 shrink-0"></span>
                    Depth: {Math.round(currentZ)}cm
                </div>
            </div>

            <div className="flex items-center gap-2 md:gap-3">
                 <button 
                    onClick={handleDownloadPDF}
                    disabled={isExporting}
                    className="flex items-center gap-2 bg-slate-900 hover:bg-slate-800 text-white px-3 py-1.5 md:px-4 md:py-2 rounded-lg text-xs md:text-sm font-bold transition-all shadow-md active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                 >
                    {isExporting ? 'Generating PDF...' : <span className="hidden sm:inline">Download PDF Report</span>}
                    {!isExporting && <svg className="w-4 h-4 sm:hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>}
                 </button>

                 <div className="flex items-center bg-slate-100 p-1 rounded-lg border border-slate-200 shrink-0">
                    <button 
                        onClick={() => setCurrentLayerIndex(Math.max(0, currentLayerIndex - 1))}
                        disabled={currentLayerIndex === 0}
                        className="p-1.5 md:p-2 hover:bg-white rounded-md shadow-sm disabled:shadow-none disabled:opacity-30 transition-all text-slate-700"
                    >
                        <svg className="w-4 h-4 md:w-5 md:h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
                    </button>
                    <div className="w-px h-4 md:h-6 bg-slate-200 mx-1"></div>
                    <button 
                        onClick={() => setCurrentLayerIndex(Math.min(layers.length - 1, currentLayerIndex + 1))}
                        disabled={currentLayerIndex === layers.length - 1}
                        className="p-1.5 md:p-2 hover:bg-white rounded-md shadow-sm disabled:shadow-none disabled:opacity-30 transition-all text-slate-700"
                    >
                        <svg className="w-4 h-4 md:w-5 md:h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                    </button>
                 </div>
            </div>
        </div>

        {/* 2D CANVAS STAGE */}
        <div className="flex-1 relative flex items-center justify-center bg-slate-200/50 overflow-hidden p-2 md:p-8" ref={containerRef}>
            
            {/* The Container Representation */}
            <div 
                className="relative bg-[#1e293b] shadow-2xl transition-all duration-300 rounded-sm md:rounded-lg overflow-hidden border-2 md:border-4 border-slate-700 ring-1 ring-white/20"
                style={{
                    width: containerDimensions.width * scale,
                    height: containerDimensions.height * scale,
                    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
                }}
            >
                {/* Inner Dark Background Grid */}
                <div className="absolute inset-0 opacity-10" 
                     style={{ backgroundImage: 'linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)', backgroundSize: '20px 20px' }}>
                </div>
                
                {/* Measurement Labels (Inside Frame) - Hidden on very small scales */}
                {scale > 0.5 && (
                    <>
                        <div className="absolute top-1 left-1 md:top-2 md:left-2 text-[8px] md:text-[10px] text-slate-500 font-mono">0,0</div>
                        <div className="absolute top-1 right-1 md:top-2 md:right-2 text-[8px] md:text-[10px] text-slate-500 font-mono">{containerDimensions.width}</div>
                        <div className="absolute bottom-1 left-1 md:bottom-2 md:left-2 text-[8px] md:text-[10px] text-slate-500 font-mono">{containerDimensions.height}</div>
                    </>
                )}

                {/* Items */}
                {activeItems.map((item, i) => {
                    // Distinction logic: New vs Existing
                    const isNew = Math.abs(item.z - currentZ) < 0.5;
                    
                    // Smart labeling: Scale logic improved for visibility
                    const boxPixelWidth = item.width * scale;
                    const boxPixelHeight = item.height * scale;
                    const showLabel = boxPixelWidth > 35 && boxPixelHeight > 20;
                    const showSmallLabel = !showLabel && boxPixelWidth > 15 && boxPixelHeight > 8;

                    return (
                        <div
                            key={i}
                            // On click prop
                            onClick={() => onPackageClick && onPackageClick(item.packageId)}
                            className={`absolute flex items-center justify-center transition-all duration-300 border-box cursor-pointer hover:brightness-110 hover:ring-2 hover:ring-white/50
                                ${isNew ? 'z-10 shadow-lg' : 'z-0 opacity-25 grayscale brightness-50'}`}
                            style={{
                                left: `${(item.x / containerDimensions.width) * 100}%`,
                                bottom: `${(item.y / containerDimensions.height) * 100}%`,
                                width: `${(item.width / containerDimensions.width) * 100}%`,
                                height: `${(item.height / containerDimensions.height) * 100}%`,
                                backgroundColor: item.color,
                                border: isNew ? '1px solid rgba(255,255,255,0.5)' : '1px dashed rgba(255,255,255,0.2)'
                            }}
                        >
                            {/* Detailed Label */}
                            {showLabel && (
                                <div className="flex flex-col items-center justify-center leading-none text-center p-0.5 overflow-hidden w-full">
                                    <span className={`font-bold drop-shadow-md truncate w-full px-1 ${isNew ? 'text-white' : 'text-white/70'}`}
                                          style={{ fontSize: Math.max(9, Math.min(16, boxPixelWidth / 4)) + 'px' }}>
                                        {Math.round(item.width)}×{Math.round(item.height)}
                                    </span>
                                    {isNew && boxPixelHeight > 40 && (
                                        <span className="text-[7px] md:text-[9px] uppercase tracking-wider text-white/80 mt-0.5 font-medium truncate w-full px-1">{item.label}</span>
                                    )}
                                </div>
                            )}
                            
                            {/* Minimal Label for small boxes */}
                            {showSmallLabel && (
                                <div className="w-1 h-1 md:w-1.5 md:h-1.5 rounded-full bg-white/50"></div>
                            )}
                        </div>
                    );
                })}
            </div>
            
            {/* Context Legend Floating */}
            <div className="absolute bottom-4 md:bottom-8 bg-white/90 backdrop-blur-sm px-3 py-1.5 md:pl-2 md:pr-4 md:py-2 rounded-full shadow-lg border border-slate-200 flex gap-3 md:gap-6 text-[10px] md:text-xs font-bold text-slate-600 animate-in fade-in slide-in-from-bottom-4 pointer-events-none z-50">
                <div className="flex items-center gap-1.5">
                    <span className="w-4 h-4 md:w-6 md:h-6 rounded-full bg-brand-500 border-2 border-white shadow-sm flex items-center justify-center text-[8px] md:text-[10px] text-white">★</span>
                    Load Now
                </div>
                <div className="h-3 md:h-4 w-px bg-slate-300"></div>
                <div className="flex items-center gap-1.5 opacity-60">
                    <span className="w-4 h-4 md:w-6 md:h-6 rounded-full bg-slate-500 grayscale border-2 border-white/50 shadow-sm"></span>
                    Past
                </div>
            </div>

        </div>

        {/* --- HIDDEN PDF RENDERER (Offscreen) --- */}
        <div className="fixed top-0 left-0 pointer-events-none opacity-0 overflow-hidden" style={{ zIndex: -1 }}>
             <PDFExportTemplate 
                ref={exportRef}
                data={data}
                layerIndex={exportLayerIndex}
                mode={exportMode}
             />
        </div>

    </div>
  );
};

export default Visualizer;